{
  "openapi": "3.0.0",
  "info": {
    "title": "Used Item Market API",
    "version": "1.0"
  },
  "servers": [
    {
      "url": "http://localhost:3000/api"
    }
  ],
  "paths": {
    "/users": {
      "post": {
        "summary": "Register new user",
        "operationId": "post-users",
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "username": {
                      "type": "string"
                    },
                    "birthDate": {
                      "type": "string"
                    },
                    "contactInformation": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "email": {
                          "type": "string"
                        },
                        "phoneNumber": {
                          "type": "string"
                        }
                      }
                    },
                    "_id": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "username": "mattimei",
                      "birthDate": "1999-02-20",
                      "contactInformation": {
                        "name": "Matti Meikäläinen",
                        "email": "matti.m@mail.com",
                        "phoneNumber": "+358 40 1234 567"
                      },
                      "_id": "5f79fcfb70f5de5ebcd9803e"

                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        },
        "description": "Endpoint for creating a new user",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "username": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  },
                  "birthDate": {
                    "type": "string",
                    "description": "ISO 8601"
                  },
                  "contactInformation": {
                    "type": "object",
                    "required": [
                      "name"
                    ],
                    "properties": {
                      "name": {
                        "type": "string"
                      },
                      "email": {
                        "type": "string",
                        "description": "At least one of phone number or email is required"
                      },
                      "phoneNumber": {
                        "type": "string",
                        "description": "At least one of phone number or email is required"
                      }
                    }
                  }
                },
                "required": [
                  "username",
                  "password",
                  "birthDate",
                  "contactInformation"
                ]
              },
              "examples": {
                "example-1": {
                  "value": {
                    "username": "mattimei",
                    "password": "MKO098UHB",
                    "birthDate": "1999-02-20",
                    "contactInformation": {
                      "name": "Matti Meikäläinen",
                      "email": "matti.m@mail.com",
                      "phoneNumber": "+358 40 1234 567"
                    }
                  }
                }
              }
            },
            "application/xml": {
              "schema": {
                "type": "object",
                "properties": {}
              }
            },
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {}
              }
            },
            "text/html": {
              "schema": {
                "type": "object",
                "properties": {}
              }
            }
          }
        }
      }
    },
    "/users/{id}": {
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "id",
          "in": "path",
          "required": true
        }
      ],
      "get": {
        "summary": "Get selected user information",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "username": {
                      "type": "string"
                    },
                    "birthDate": {
                      "type": "string",
                      "description": "ISO 8601"
                    },
                    "contactInformation": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "email": {
                          "type": "string"
                        },
                        "phoneNumber": {
                          "type": "string"
                        }
                      }
                    },
                    "_id": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "username": "mattimei",
                      "birthDate": "1999-02-20",
                      "contactInformation": {
                        "name": "Matti Meikäläinen",
                        "email": "matti.m@mail.com",
                        "phoneNumber": "+358 40 1234 567"
                      },
                      "_id": "4f8313a89231d42189ac"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        },
        "operationId": "get-users-id",
        "description": "Endpoint for user to get their own information",
        "parameters": [],
        "security": [
          {
            "User Authorization": []
          }
        ]
      },
      "put": {
        "summary": "Modify user's own information",
        "operationId": "put-users-id",
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        },
        "description": "Endpoint for user to modify their own information",
        "security": [
          {
            "User Authorization": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "username": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  },
                  "birthDate": {
                    "type": "string",
                    "description": "ISO 8601"
                  },
                  "contactInformation": {
                    "type": "object",
                    "properties": {
                      "name": {
                        "type": "string"
                      },
                      "email": {
                        "type": "string"
                      },
                      "phoneNumber": {
                        "type": "string"
                      }
                    }
                  }
                }
              }
            }
          },
          "description": "Request body for modifying user data. All fields optional"
        }
      },
      "delete": {
        "summary": "Delete user account",
        "operationId": "delete-users-id",
        "responses": {
          "200": {
            "description": "OK"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        },
        "description": "Endpoint for deleting selected user account",
        "security": [
          {
            "User Authorization": []
          }
        ]
      }
    },
    "/auth/login": {
      "get": {
        "summary": "Log in user",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "token": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        },
        "operationId": "get-auth-login",
        "security": [
          {
            "HTTPBasic for login": []
          }
        ],
        "description": "Endpoint for user to log in and obtain an authentication token"
      }
    }
  },
  "components": {
    "schemas": {
      "User": {
        "title": "User",
        "type": "object",
        "description": "User model",
        "x-examples": {
          "example-1": {
            "username": "mattimei",
            "password": "MKO098UHB",
            "birthDate": "1999-02-20",
            "contactInformation": {
              "name": "Matti Meikäläinen",
              "email": "matti.m@mail.com",
              "phoneNumber": "+358 40 1234 567"
            },
            "_id": "4f8313a89231d42189ac"
          }
        },
        "properties": {
          "username": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "birthDate": {
            "type": "string",
            "description": "ISO 8601"
          },
          "contactInformation": {
            "type": "object",
            "required": [
              "name"
            ],
            "properties": {
              "name": {
                "type": "string"
              },
              "email": {
                "type": "string",
                "description": "At least one of phone number or email is required"
              },
              "phoneNumber": {
                "type": "string",
                "description": "At least one of phone number or email is required"
              }
            }
          },
          "_id": {
            "type": "string",
            "description": "Generated by MongoDB"
          }
        },
        "required": [
          "username",
          "password",
          "birthDate",
          "contactInformation",
          "_id"
        ]
      },
      "ErrorResponse": {
        "title": "ErrorResponse",
        "type": "object",
        "properties": {
          "errorDescription": {
            "type": "string"
          }
        },
        "description": "Error response object model",
        "x-examples": {
          "example-1": {
            "errorDescription": "Request failed due to unknown error"
          }
        }
      }
    },
    "securitySchemes": {
      "HTTPBasic for login": {
        "type": "http",
        "scheme": "basic",
        "description": ""
      },
      "User Authorization": {
        "type": "http",
        "scheme": "bearer",
        "description": ""
      }
    }
  }
}